#!/usr/bin/perl
# Copyright (c) 2011
# Distilled Media Ltd.  All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
# 3. Neither the name of the author nor the names of any contributors to the
#    software may be used to endorse or promote products derived from this
#    software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

#
# Monitors the amount of time since a FreeBSD OS passed its end-of-life.
#

use strict;
use warnings;

use POSIX;

# End of life dates for each release.
my %KNOWN_EOLS = (
    '6.0' => POSIX::mktime(0, 0, 0, 30, 10, 106),
    '6.1' => POSIX::mktime(0, 0, 0, 31, 4, 108),
    '6.2' => POSIX::mktime(0, 0, 0, 31, 4, 108),
    '6.3' => POSIX::mktime(0, 0, 0, 31, 0, 110),
    '6.4' => POSIX::mktime(0, 0, 0, 30, 10, 110),
    '7.0' => POSIX::mktime(0, 0, 0, 30, 3, 109),
    '7.1' => POSIX::mktime(0, 0, 0, 31, 0, 111),
    '7.2' => POSIX::mktime(0, 0, 0, 30, 5, 110),
    '7.3' => POSIX::mktime(0, 0, 0, 31, 2, 112),
    '7.4' => POSIX::mktime(0, 0, 0, 28, 1, 113),
    '8.0' => POSIX::mktime(0, 0, 0, 30, 10, 110),
    '8.1' => POSIX::mktime(0, 0, 0, 31, 6, 112),
    '8.2' => POSIX::mktime(0, 0, 0, 29, 1, 112),
);

# Configuration
if ($ARGV[0] && $ARGV[0] eq "config") {
    print "graph_title OS Days Since EOL\n";
    print "graph_vlabel days\n";
    print "graph_category system\n";
    print "eol.label eol\n";
    exit(0);
}

# Get the release
my $release = `/usr/bin/uname -r`;
chomp $release;
$release =~ s/^(\d+(?:\.\d+)*).*$/$1/o;

# Find the number of days since the EOL.
my $eol_time = 0;
if ($KNOWN_EOLS{$release}) {
    $eol_time = time() - $KNOWN_EOLS{$release};
}
$eol_time /= 86400;
if ($eol_time < 0) {
    $eol_time = 0;
} elsif ($eol_time > 720) {
    # Cap it at 720 days to prevent graphs getting screwed up by ancient
    # releases.
    $eol_time = 720;
}

printf("eol.value %.1f\n", $eol_time);
