#!/usr/bin/perl
# Copyright (c) 2011
# Distilled Media Ltd.  All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
# 3. Neither the name of the author nor the names of any contributors to the
#    software may be used to endorse or promote products derived from this
#    software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

#
# Monitors swap usage on a FreeBSD system.
#

use strict;
use warnings;

my %devices;
if (open(SWAPCTL, "/sbin/swapctl -lk|")) {
	while (<SWAPCTL>) {
		if (!/^Device:\s+/o) {
			my ($dev, $size, $used) = split;
			my $name = $dev;
			$dev =~ s/\W+/_/go;
			$devices{$dev}{'size'} = ($size * 1024);
			$devices{$dev}{'used'} = ($used * 1024);
			$devices{$dev}{'name'} = $name;
		}
	}
	close(SWAPCTL);
}

if (@ARGV && $ARGV[0] eq 'config') {
	print "graph_title Swap Usage\n";
	print "graph_args -l 0 --base 1024\n";
	print "graph_vlabel bytes\n";
	print "graph_category disk\n";
	foreach (sort keys %devices) {
		printf("%s.label %s\n", $_, $devices{$_}{'name'});
		printf("%s.warning %d\n", $_, ($devices{$_}{'size'} * 0.50));
		printf("%s.critical %d\n", $_, ($devices{$_}{'size'} * 0.80));
	}
} else {
	foreach (sort keys %devices) {
		printf("%s.value %d\n", $_, $devices{$_}{'used'});
	}
}
